# command to run:
# docker-compose -f docker-comp-test.yml up

# This will start dependencies container & postgres db container with it's associated data volumes container
# and run 'npm run test'

version: "3"
services:

  test:
    image: <docker-org-name>/<app-name>-dependencies
    container_name: <app-name>-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules_test:/usr/src/app/node_modules
    depends_on:
      - postgres-db-test
      - postgres-data-test
    command: ["./scripts/postgres-db/run-migrate.sh", "postgres-db-test", "${DATABASE_MIGRATIONS}", "test-coverage", "${DATABASE_TEST_SCOPES}"]

  postgres-db-test:
    environment:
      - POSTGRES_PASSWORD=<db-password>
      - POSTGRES_USER=<db-username>
      - POSTGRES_DB=<db-name>
    image: <docker-org-name>/<app-name>-postgres
    container_name: <app-name>-postgres-db-test
    volumes:
      - test-db-volume:/var/lib/postgresql/data
      - ./scripts/postgres-db:/postgres-db

# shared volumes
volumes:
  test-db-volume:
  node_modules_test:
